import React from 'react';

const Page = () => {
    return (
        <div className="p-6 bg-gray-50 text-gray-800">
            <h1 className="text-3xl font-bold mb-4">Privacy Policy of Easyfy</h1>
            <p className="text-sm text-gray-600 mb-6">Last updated: December 27, 2024</p>
            <p className="mb-4 leading-6">
                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p className="mb-6 leading-6">
                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the 
                <a 
                    href="https://www.termsfeed.com/privacy-policy-generator/" 
                    target="_blank" 
                    rel="noopener noreferrer" 
                    className="text-blue-500 hover:underline"
                >Privacy Policy Generator</a>.
            </p>
            <h2 className="text-2xl font-semibold mt-8 mb-4">Interpretation and Definitions</h2>

            <h3 className="text-xl font-medium mb-3">Interpretation</h3>
            <p className="mb-4 leading-6">
                The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="text-xl font-medium mb-3">Definitions</h3>
            <p className="mb-4 leading-6">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-5 mb-6 space-y-2">
                <li>
                    <p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
                </li>
                <li>
                    <p><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
                </li>
                <li>
                    <p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Easyfy.</p>
                </li>
                <li>
                    <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
                </li>
                <li>
                    <p><strong>Country</strong> refers to: Delhi, India</p>
                </li>
                <li>
                    <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
                </li>
                <li>
                    <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
                </li>
                <li>
                    <p><strong>Service</strong> refers to the Website.</p>
                </li>
                <li>
                    <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
                </li>
                <li>
                    <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                </li>
                <li>
                    <p><strong>Website</strong> refers to Easyfy, accessible from 
                        <a 
                            href="https://www.easyfy.website/" 
                            rel="external nofollow noopener" 
                            target="_blank" 
                            className="text-blue-500 hover:underline"
                        >https://www.easyfy.website/</a>
                    </p>
                </li>
                <li>
                    <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
                </li>
            </ul>

            <h2 className="text-2xl font-semibold mt-8 mb-4">Collecting and Using Your Personal Data</h2>

            <h3 className="text-xl font-medium mb-3">Types of Data Collected</h3>
            <h4 className="text-lg font-medium mb-2">Personal Data</h4>
            <p className="mb-4 leading-6">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-5 mb-6">
                <li>Usage Data</li>
            </ul>
            
            {/* Add more sections as per the content */}

            <h2 className="text-2xl font-semibold mt-8 mb-4">Contact Us</h2>
            <p className="mb-4 leading-6">If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul className="list-disc pl-5 mb-6">
                <li>By email: <a href="mailto:hamzacontact247@gmail.com" className="text-blue-500 hover:underline">hamzacontact247@gmail.com</a></li>
                <li>By phone number: <a href="tel:+8700362783" className="text-blue-500 hover:underline">8700362783</a></li>
            </ul>
        </div>
    );
};

export default Page;
